package io.github.wouterbauweraerts.instancio.fixture.builder.generator;

import static javax.lang.model.element.Modifier.PUBLIC;

import java.io.IOException;
import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;
import java.util.List;

import javax.annotation.processing.Generated;
import javax.annotation.processing.ProcessingEnvironment;
import javax.lang.model.element.AnnotationMirror;
import javax.lang.model.element.Element;
import javax.lang.model.type.TypeMirror;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.ClassName;
import com.palantir.javapoet.JavaFile;
import com.palantir.javapoet.MethodSpec;
import com.palantir.javapoet.ParameterizedTypeName;
import com.palantir.javapoet.TypeSpec;

import io.github.wouterbauweraerts.instancio.fixture.builder.AbstractFixtureBuilder;
import io.github.wouterbauweraerts.instancio.fixture.builder.InstancioModel;
import io.github.wouterbauweraerts.instancio.fixture.builder.generator.exception.FixtureBuilderGenerationException;

public class FixtureBuilderGenerator {
    private static final String FIXTURE_BUILDER_SUFFIX = "FixtureBuilder";
    public static final String BUILDER_FOR_TYPE = "builderForType";
    public static final String FIXTURE_CLASS_TYPE = "fixtureClass";

    private final ProcessingEnvironment processingEnv;
    private final BuilderMethodFactory methodFactory;

    public FixtureBuilderGenerator(ProcessingEnvironment processingEnv) {
        this.processingEnv = processingEnv;
        methodFactory = FactoryProvider.builderMethodFactory();
    }

    public void generateFixtureBuilders(Element fixtureBuilderElement) {
        AnnotationMirror annotationMirror = processingEnv.getElementUtils().getAllAnnotationMirrors(fixtureBuilderElement).stream()
                .filter(am -> am.getAnnotationType().toString().equals("io.github.wouterbauweraerts.instancio.fixture.builder.GenerateFixtureBuilder"))
                .findFirst().orElseThrow(FixtureBuilderGenerationException::unableToReadAnnotation);

        Element typeToBuild = getType(processingEnv, annotationMirror, BUILDER_FOR_TYPE);
        Element fixtureClassType = getType(processingEnv, annotationMirror, FIXTURE_CLASS_TYPE);
        Element model = fixtureClassType.getEnclosedElements().stream()
                .filter(e -> e.getAnnotation(InstancioModel.class) != null)
                .findFirst()
                .orElseThrow(FixtureBuilderGenerationException::modelNotFound);

        String builderClassName = typeToBuild.getSimpleName() + FIXTURE_BUILDER_SUFFIX;

        MethodSpec self = methodFactory.generateSelf(builderClassName);
        MethodSpec build = methodFactory.generateBuild(model, typeToBuild.getSimpleName().toString());
        List<MethodSpec> builderMethods = methodFactory.generateFieldMethods(processingEnv, typeToBuild, builderClassName);

        AnnotationSpec generatedAnnotation = AnnotationSpec.builder(Generated.class)
                .addMember("value", "$S", "Generated by instancio-fixture-builder annotation processor on %s".formatted(LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME)))
                .build();
        TypeSpec builder = TypeSpec.classBuilder(builderClassName)
                .addModifiers(PUBLIC)
                .addAnnotation(generatedAnnotation)
                .superclass(
                        ParameterizedTypeName.get(
                                ClassName.get(AbstractFixtureBuilder.class),
                                ClassName.bestGuess(typeToBuild.getSimpleName().toString()),
                                ClassName.bestGuess(builderClassName)
                        )
                )
                .addMethod(self)
                .addMethod(build)
                .addMethods(builderMethods)
                .build();

        JavaFile javaFile = JavaFile.builder(processingEnv.getElementUtils().getPackageOf(typeToBuild).getQualifiedName().toString(), builder)
                .addStaticImport(ClassName.get(
                        processingEnv.getElementUtils().getPackageOf(fixtureClassType).getQualifiedName().toString(),
                        fixtureClassType.getSimpleName().toString()
                ), model.getSimpleName().toString())
                .build();
        try {
            javaFile.writeTo(processingEnv.getFiler());
        } catch (IOException e) {
            throw FixtureBuilderGenerationException.writeException(e.getMessage());
        }
    }

    private Element getType(ProcessingEnvironment processingEnv, AnnotationMirror mirror, String keyValue) {
        return processingEnv.getElementUtils().getElementValuesWithDefaults(mirror).entrySet().stream()
                .filter(e -> e.getKey().getSimpleName().contentEquals(keyValue))
                .map(e -> e.getValue().getValue())
                .map(it -> processingEnv.getTypeUtils().asElement((TypeMirror) it))
                .findFirst()
                .orElseThrow(() -> FixtureBuilderGenerationException.missingValue(keyValue));
    }
}
