package io.github.wouterbauweraerts.instancio.fixture.builder.generator;

import java.time.LocalDateTime;
import java.time.format.DateTimeFormatter;

import javax.annotation.processing.Generated;

import com.palantir.javapoet.AnnotationSpec;

class GeneratedAnnotationFactory {
    static final String GENERATED_ANNOTATION_MSG = "Generated by instancio-fixture-builder annotation processor on %s";

    AnnotationSpec createAnnotation() {
        return AnnotationSpec.builder(Generated.class)
                .addMember("value", "$S", GENERATED_ANNOTATION_MSG.formatted(LocalDateTime.now().format(DateTimeFormatter.ISO_DATE_TIME)))
                .build();
    }

}
