remote_theme: pages-themes/slate@v0.2.0
plugins:
  - jekyll-remote-theme

title: Instancio Extension - Fixture Builder
description: Describe how the instancio-fixture-builder can be used
show_downloads: false