package io.github.wouterbauweraerts.instancio.fixture.builder.generator;

import static org.assertj.core.api.Assertions.assertThat;

import java.util.regex.Pattern;

import org.junit.jupiter.api.Test;

import com.palantir.javapoet.AnnotationSpec;
import com.palantir.javapoet.CodeBlock;

class GeneratedAnnotationFactoryTest {
    private static final Pattern GENERATED_PATTERN = Pattern.compile("\"Generated by instancio-fixture-builder annotation processor on [0-9]{4}-[0-9]{2}-[0-9]{2}T[0-9]{2}:[0-9]{2}:[0-9]{2}.*\"");
    GeneratedAnnotationFactory factory = new GeneratedAnnotationFactory();

    @Test
    void createAnnotation_returnsExpectedAnnotationSpec() {
        AnnotationSpec annotation = factory.createAnnotation();

        assertThat(annotation.type()).hasToString("javax.annotation.processing.Generated");
        assertThat(annotation.members().get("value")).isNotNull()
                .hasSize(1)
                .extracting(CodeBlock::toString)
                .allMatch(s -> GENERATED_PATTERN.matcher(s).matches());
    }
}